---

- name: 'Include arillso.system.apt_cache role'
  ansible.builtin.include_role:
    name: arillso.system.apt_cache

- name: 'Check availability updates Debian'
  become: true
  arillso.system.apt_update_info:
  register: register_update

- name: Run arillso Apt Package
  ansible.builtin.include_role:
    name: arillso.system.apt_packages
    tasks_from: install_apt_package
  loop: "{{ register_update.packages }}"
  loop_control:
    loop_var: apt_package
  vars:
    apt_package_name: "{{ apt_package.package }}"
    apt_package_version: "{{ apt_package.available }}"
