---
- name: "Include arillso.system.apt_cache role"
  ansible.builtin.include_role:
    name: arillso.system.apt_cache

- name: "Check availability updates Debian"
  become: true
  arillso.system.apt_update_info:
  register: register_update

- name: Convert package list and run arillso Apt Package role
  ansible.builtin.include_role:
    name: arillso.system.apt_packages
  vars:
    apt_packages_list: >-
      {{
        register_update.packages | map('dict', {'name': item.package, 'version': item.available}) | list
      }}
