---
- name: Restart systemd-resolved to apply DNS resolver changes
  ansible.builtin.systemd:
      name: systemd-resolved
      state: restarted
  when: network_systemd_resolved_restart | default(true)
  listen: "network: restart resolved"

- name: Restart systemd-networkd to apply network interface changes
  ansible.builtin.systemd:
      name: systemd-networkd
      state: restarted
  when: network_systemd_networkd_restart | default(false)
  listen: "network: restart networkd"
