---

- name: ensure stopped systemd-resolved
  ansible.builtin.include_role:
    name: arillso.system.systemd_service
  vars:
    systemd_service_name: systemd-resolved
    systemd_service_enabled: false
    systemd_service_state: stopped

- name: ensure resolv
  ansible.builtin.import_tasks: configure_resolv.yml
