---
_pip_packages:
  Alpine:
    - name: py3-pip
    - name: py3-setuptools
    - name: python3-dev
  Debian:
    - name: python3-pip
    - name: python3-setuptools
  RedHat: &redhat_packages
    - name: python3-pip
    - name: python3-setuptools
  Rocky: *redhat_packages

pip_packages: "{{ _pip_packages[ansible_os_family] }}"
