---
_pip_packages:
  Alpine:
    - py3-pip
    - py3-setuptools
    - python3-dev
  Debian:
    - python3-pip
    - python3-setuptools
  RedHat: &redhat_packages
    - python3-pip
    - python3-setuptools
  Rocky: *redhat_packages

pip_packages: "{{ _pip_packages[ansible_os_family] }}"
