---
- name: Restart iptables
  become: true
  ansible.builtin.service:
    name: "{{ iptables_ipv4_service }}"
    state: restarted

- name: Start iptables
  become: true
  ansible.builtin.service:
    name: "{{ iptables_ipv4_service }}"
    state: started

- name: Enable iptables
  become: true
  ansible.builtin.service:
    name: "{{ iptables_ipv4_service }}"
    enabled: true

- name: Restart iptables 6
  become: true
  ansible.builtin.service:
    name: "{{ iptables_ipv6_service }}"
    state: restarted

- name: Start iptables 6
  become: true
  ansible.builtin.service:
    name: "{{ iptables_ipv6_service }}"
    state: started
  when: "'scope' in ansible_default_ipv6 and ansible_default_ipv6.scope == 'global'"

- name: Enable iptables 6
  become: true
  ansible.builtin.service:
    name: "{{ iptables_ipv6_service }}"
    enabled: true
  when: "'scope' in ansible_default_ipv6 and ansible_default_ipv6.scope == 'global'"
