---
# Argument specifications for iptables rules
argument_specs:
  main:
    description:
      - Manage the Message of the Day (MOTD) configuration including creation, modification, and deletion of MOTD content.
    short_description: Manage MOTD configuration
    options:
      motd_header:
        description: The header text for the Message of the Day (MOTD) script
        type: str
        default: |
          -
            _              _ _     _
            / \   _ __  ___(_) |__ | | ___
            / _ \ | '_ \/ __| | '_ \| |/ _ \
          / ___ \| | | \__ \ | |_) | |  __/
          /_/   \_\_| |_|___/_|_.__/|_|\___|

      motd_fqdn:
        description: Fully Qualified Domain Name of the host
        type: str
        default: "{{ ansible_fqdn }}"

      motd_distribution:
        description: Operating System Distribution Name
        type: str
        default: "{{ ansible_distribution }}"

      motd_distribution_version:
        description: Operating System Distribution Version
        type: str
        default: "{{ ansible_distribution_version }}"

      motd_distribution_release:
        description: Release name of the distribution
        type: str
        default: "{{ ansible_distribution_release }}"

      motd_virtualization_role:
        description: Role in virtualization (guest/host/none)
        type: str
        default: "{{ ansible_virtualization_role }}"

      motd_virtualization_type:
        description: Type of virtualization (KVM, VirtualBox, etc.)
        type: str
        default: "{{ ansible_virtualization_type }}"

      motd_date_time:
        description: Date and time information
        type: dict
        options:
          tz:
            description: Timezone of the motd_date_time
            type: str
            default: "{{ ansible_date_time.tz }}"
          tz_offset:
            description: Timezone offset of the motd_date_time
            type: str
            default: "{{ ansible_date_time.tz_offset }}"

      motd_region:
        description: Region variable
        type: str
        default: undefined

      motd_zone:
        description: Zone variable
        type: str
        default: undefined

      motd_customer:
        description: Customer variable
        type: str
        default: undefined

      motd_projects:
        description: Projects variable
        type: list
        default: undefined

      motd_project:
        description: Single project variable
        type: str
        default: undefined

      motd_exclude_disk_space:
        description: List of filesystem types to exclude in disk space check
        type: list
        default:
          - tmpfs
          - devtmpfs
          - overlay
