---
- name: Converge — arillso.system.shell
  hosts: all
  become: true

  vars:
      shell_motd_enabled: true
      shell_ssh_banner_enabled: true
      shell_enable_background_processing: false
      shell_facts_dependency: false

  tasks:
      - name: Apply shell role
        ansible.builtin.include_role:
            name: arillso.system.shell
