version: 2
# Specifies the configuration version for Dependabot. Version 2 is the latest version.

updates:
  # Configuration for updating GitHub Actions
  - package-ecosystem: "github-actions"
    # Specifies that GitHub Actions is the package ecosystem to be updated.
    directory: "/"
    # Sets the directory within the repository where Dependabot looks for GitHub Actions definitions.
    # "/" indicates the root directory of the repository.

    schedule:
      interval: "weekly"
      # Defines the update frequency. "weekly" means Dependabot checks for updates once a week.
      day: "friday"
      # Specifies the day of the week when Dependabot should run, set here to Friday.
      time: "13:00"
      # Sets the time for the Dependabot run. "13:00" is 1:00 PM UTC, corresponding to 2:00 PM in Zurich during winter.

    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
      # Configures the commit message settings for Dependabot.
      # 'prefix' and 'prefix-development' set a prefix for commit messages.
      # 'include: "scope"' includes the scope of the dependencies in the commit message.

    assignees:
      - "sbaerlocher"
      # Specifies GitHub users to be automatically assigned to Dependabot pull requests.
      # Here, 'sbaerlocher' is the user who will be assigned to the pull requests.
