---
argument_specs:
  repositories: &repositories
    short_description: Manage APT repositories
    description:
      - This specification manages the addition, modification, and removal of APT repositories on a system.
    options:
      apt_repositories_list:
        type: list
        elements: dict
        description:
          - A list of dictionaries specifying APT repositories to manage.
        default: []
        options:
          codename:
            type: str
            description: Codename of the distribution version for the repository.
          filename:
            type: str
            description: Filename under which the repository is stored.
            default: "{{ apt_repositories_filename }}"
          install_python_apt:
            type: bool
            description: Whether to install the python-apt package if necessary for the repository.
          mode:
            type: str
            description: File permissions for the repository file.
          repo:
            type: str
            description: Repository entry line (e.g., 'deb http://myrepo.example.com/debian buster main').
          state:
            type: str
            description: State of the repository ('present' or 'absent').
            default: "present"
          update_cache_retries:
            type: int
            description: Number of retries to update the cache after adding the repository.
            default: "{{ apt_repositories_update_cache_retries }}"
          update_cache_retry_max_delay:
            type: int
            description: Maximum delay in seconds between retries to update the cache.
            default: "{{ apt_repositories_update_cache_retry_max_delay }}"
          update_cache:
            type: bool
            description: Whether to update the cache after adding the repository.
            default: "{{ apt_repositories_update_cache }}"
          validate_certs:
            type: bool
            description: Whether to validate SSL certificates for HTTPS repositories.

      apt_repositories_filename:
        type: str
        description: Default filename for APT repositories if not specified in each repository dictionary.
        default: "default.list"

      apt_repositories_update_cache_retries:
        type: int
        description: Default value for the number of retries to update the cache after adding a repository.
        default: 5

      apt_repositories_update_cache_retry_max_delay:
        type: int
        description: Default maximum delay in seconds between retries to update the cache.
        default: 12

      apt_repositories_update_cache:
        type: bool
        description: Default value to decide whether to update the cache after adding a repository.
        default: true

  main: *repositories
