---

galaxy_info:
  description: apt repositories role
  author: "arillso (@arillso)"
  license: MIT
  min_ansible_version: "2.11"
  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: Ubuntu
      versions:
        - focal

  galaxy_tags:
    - repositories
    - repository
    - apt

dependencies:
  - role: arillso.system.apt_cache
