---

- name: Configuration specific files
  become: true
  ansible.builtin.template:
    src: etc/sudoers.d/sudoers.j2
    dest: '/etc/sudoers.d/{{ item.key }}'
    validate: 'visudo -cf %s'
    owner: root
    group: root
    mode: 0440
  with_dict: '{{ sudoers_sudoers_d_files }}'

- name: Configuration global files
  become: true
  ansible.builtin.template:
    src: etc/sudoers.j2
    dest: '{{ sudoers_sudoers_file }}'
    validate: 'visudo -cf %s'
    owner: root
    group: root
    mode: 0440
