---
- name: Add OS specific variables
  ansible.builtin.include_vars: "{{ loop_vars }}"
  with_first_found:
    - files:
        - "{{ distribution }}-{{ distribution_version }}.yml"
        - "{{ distribution }}-{{ distribution_major_version }}.yml"
        - "{{ distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "{{ ansible_system }}.yml"
        - "defaults.yml"
      paths:
        - "vars"
  loop_control:
    loop_var: loop_vars
  vars:
    distribution: "{{ ansible_distribution }}"
    distribution_version: "{{ ansible_distribution_version }}"
    distribution_major_version: "{{ ansible_distribution_major_version }}"

- name: Include distribution install tasks
  ansible.builtin.include_tasks: "install_sudores.yml"

- name: Include distribution configure tasks
  ansible.builtin.include_tasks: "configure_sudores.yml"
