---
argument_specs:
  main: &main
    description:
      - Manages environment variables by setting them in specified files.
    short_description: Manage environment variables in files
    options:
      environment_files:
        type: list
        elements: str
        description:
          - A list of files where environment variables will be set.
          - Each entry in the list is a path to a file.
        default: []

      environment_variables:
        type: dict
        description:
          - A dictionary of environment variables to set.
          - Keys are the names of the variables, and values are the values of these variables.
        default: {}

  variables: *main
