---
APPLY_FIXES: all

EXCLUDED_PATHS:
  - ".ansible/**"

DISABLE_LINTERS:
  - CSS_STYLELINT
  - JSON_V8R
  - REPOSITORY_DEVSKIM
  - REPOSITORY_TRUFFLEHOG
  - SPELL_CSPELL
  - SPELL_LYCHEE
  - TERRAFORM_TERRAGRUNT
  - YAML_V8R

PARALLEL_PROCESS_NUMBER: 5
REPOSITORY_KICS_CONFIG_FILE: .kics.json
REPOSITORY_TRIVY_CONFIG_FILE: .trivy.yaml
