---
namespace: arillso
name: system
version: 1.0.4
readme: README.md

authors:
    - Simon Baerlocher (@sbaerlocher) <s.baerlocher@sbaerlocher.ch>
    - arillso (@arillso) <hello@arillso.io>

description: "This is an Ansible collection that configures system"

license:
    - MIT

tags:
    - system
    - apt
    - systemd
    - linux
    - windows

dependencies:
    ansible.posix: ">=2.0.0"
    community.general: ">=9.0.0"
    community.crypto: ">=2.0.0"

repository: https://github.com/arillso/ansible.system

documentation: https://guide.arillso.io/collections/arillso/system/index.html

homepage: https://arillso.io

issues: https://github.com/arillso/ansible.system/issues

build_ignore: []
