---
argument_specs:
  main:
    short_description: Manage Chocolatey packages
    description:
      - This specification manages the installation, upgrade, and removal of Chocolatey packages on a Windows system.
    options:
      chocolatey_packages_list:
        type: list
        elements: dict
        description:
          - A list of dictionaries specifying Chocolatey packages to manage.
        default: []
        options:
          name:
            type: str
            description: Name of the Chocolatey package.
          state:
            type: str
            description: State of the package ('present', 'absent', or 'latest').
            default: "present"
          version:
            type: str
            description: Specific version of the package to be installed. Omitted by default.
          source:
            type: str
            description: Source URL or alias of the Chocolatey package.
          install_args:
            type: str
            description: Arguments to pass to the installer.
          package_params:
            type: str
            description: Package parameters to pass.
          ignore_checksums:
            type: bool
            description: Whether to ignore checksums on packages.
          allow_empty_checksums:
            type: bool
            description: Whether to allow empty checksums for packages.
          allow_multiple:
            type: bool
            description: Whether to allow multiple versions of a package.
          allow_prerelease:
            type: bool
            description: Whether to include pre-release versions.
          architecture:
            type: str
            description: Architecture of the package (e.g., 'x86', 'x64').
          choco_args:
            type: str
            description: Additional arguments to pass to Chocolatey.
          force:
            type: bool
            description: Force the installation or upgrade of the package.
          ignore_dependencies:
            type: bool
            description: Ignore package dependencies during installation.
          override_args:
            type: bool
            description: Override default package installation arguments.
          pinned:
            type: bool
            description: Pin the package version.
          proxy_url:
            type: str
            description: URL of the proxy server.
          proxy_username:
            type: str
            description: Username for the proxy server.
          proxy_password:
            type: str
            description: Password for the proxy server.
          remove_dependencies:
            type: bool
            description: Remove package dependencies.
          skip_scripts:
            type: bool
            description: Skip running Chocolatey scripts.
          source_username:
            type: str
            description: Username for the package source.
          source_password:
            type: str
            description: Password for the package source.
          timeout:
            type: int
            description: Timeout for the installation process.
          validate_certs:
            type: bool
            description: Validate SSL certificates for the package source.
          bootstrap_script:
            type: str
            description: Script for bootstrapping Chocolatey.

  install_chocolatey_package:
    short_description: Manage Chocolatey packages
    description:
      - This specification manages the installation, upgrade, and removal of Chocolatey packages on a Windows system.
    options:
      chocolatey_packages_allow_empty_checksums:
        type: bool
        description: Allow empty checksums for packages by default.
        default: false

      chocolatey_packages_allow_multiple:
        type: bool
        description: Allow multiple versions of a package by default.
        default: false

      chocolatey_packages_allow_prerelease:
        type: bool
        description: Include pre-release versions by default.
        default: false

      chocolatey_packages_architecture:
        type: str
        description: Architecture of the package (e.g., 'x86', 'x64'), default is unset.
        default: "{{ omit }}"

      chocolatey_packages_bootstrap_script:
        type: str
        description: Script for bootstrapping Chocolatey, default is unset.
        default: "{{ omit }}"

      chocolatey_packages_choco_args:
        type: str
        description: Additional arguments to pass to Chocolatey, default is unset.
        default: "{{ omit }}"

      chocolatey_packages_force:
        type: bool
        description: Force the installation by default.
        default: false

      chocolatey_packages_ignore_checksums:
        type: bool
        description: Ignore checksums by default.
        default: false

      chocolatey_packages_ignore_dependencies:
        type: bool
        description: Ignore dependencies by default.
        default: false

      chocolatey_packages_install_args:
        type: str
        description: Additional arguments for the installer, default is unset.
        default: "{{ omit }}"

      chocolatey_packages_override_args:
        type: bool
        description: Override the default installation arguments by default.
        default: false

      chocolatey_packages_package_params:
        type: str
        description: Parameters to pass to the package, default is unset.
        default: "{{ omit }}"

      chocolatey_packages_pinned:
        type: bool
        description: Pin the package version by default.
        default: false

      chocolatey_packages_proxy_password:
        type: str
        description: Proxy password, default is unset.
        default: "{{ omit }}"

      chocolatey_packages_proxy_url:
        type: str
        description: URL of the proxy server, default is unset.
        default: "{{ omit }}"

      chocolatey_packages_proxy_username:
        type: str
        description: Username for the proxy server, default is unset.
        default: "{{ omit }}"

      chocolatey_packages_remove_dependencies:
        type: bool
        description: Remove package dependencies by default.
        default: false

      chocolatey_packages_skip_scripts:
        type: bool
        description: Skip running Chocolatey scripts by default.
        default: false

      chocolatey_packages_source:
        type: str
        description: The source to install the package from, default is unset.
        default: "{{ omit }}"

      chocolatey_packages_source_password:
        type: str
        description: Password for the package source, default is unset.
        default: "{{ omit }}"

      chocolatey_packages_source_username:
        type: str
        description: Username for the package source, default is unset.
        default: "{{ omit }}"

      chocolatey_packages_timeout:
        type: int
        description: Timeout for the installation process, default is unset.
        default: "{{ omit }}"

      chocolatey_packages_validate_certs:
        type: bool
        description: Validate SSL certificates by default.
        default: true
