---
galaxy_info:
  description: The role installs different packages on the Windows system.
  author: "arillso (@arillso)"
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: Ubuntu
      versions:
        - focal

  galaxy_tags:
    - package
    - packages
    - chocolatey

dependencies: []
