---
# Header text for the MOTD script, undefined by default
motd_header: |2-
       _              _ _     _
      / \   _ __  ___(_) |__ | | ___
     / _ \ | '_ \/ __| | '_ \| |/ _ \
    / ___ \| | | \__ \ | |_) | |  __/
   /_/   \_\_| |_|___/_|_.__/|_|\___|

# Fully Qualified Domain Name of the host
motd_fqdn: "{{ ansible_fqdn }}" # Uses Ansible's built-in FQDN fact

# Operating System Distribution Name
motd_distribution: "{{ ansible_distribution }}" # Uses Ansible's built-in distribution fact

# Operating System Distribution Version
motd_distribution_version: "{{ ansible_distribution_version }}" # Uses Ansible's built-in distribution version fact

# Release name of the distribution
motd_distribution_release: "{{ ansible_distribution_release }}" # Uses Ansible's built-in distribution release fact

# Role in virtualization (guest/host/none)
motd_virtualization_role: "{{ ansible_virtualization_role }}" # Uses Ansible's built-in virtualization role fact

# Type of virtualization (KVM, VirtualBox, etc.)
motd_virtualization_type: "{{ ansible_virtualization_type }}" # Uses Ansible's built-in virtualization type fact

# Date and time information
motd_date_time: # Uses Ansible's built-in date time fact to populate timezone and offset
  tz: "{{ ansible_date_time.tz }}" # Sets the timezone using Ansible's ansible_date_time fact
  tz_offset: "{{ ansible_date_time.tz_offset }}" # Sets the timezone offset using Ansible's ansible_date_time fact

# Region variable, undefined by default
motd_region: undefined # Custom variable, default set to 'undefined'

# Zone variable, undefined by default
motd_zone: undefined # Custom variable, default set to 'undefined'

# Customer variable, undefined by default
motd_customer: undefined # Custom variable, default set to 'undefined'

# Projects variable, undefined by default
motd_projects: undefined # Custom variable, default set to 'undefined'

# Single project variable, undefined by default
motd_project: undefined # Custom variable, default set to 'undefined'

# List of filesystem types to exclude in disk space check, empty by default
motd_exclude_disk_space:
  - tmpfs
  - devtmpfs
  - overlay
