---
# vars file for logrotate

logrotate_packages:
  - name: logrotate

logrotate_config_directory: /etc

logrotate_config_file: logrotate.conf

logrotate_confd_directory: "{{ logrotate_config_directory }}/logrotate.d"

_logrotate_user:
  default: root

_logrotate_group:
  default: root
  Debian: adm
  Ubuntu: adm
  AlmaLinux: root
  CentOS: root
  Rocky: root

_logrotate_dateext:
  default: false
  AlmaLinux: true
  CentOS: true
  Debian: false
  Rocky: true
  Ubuntu: false
