---
# logrotate_packages: Defines the packages required for log rotation.
# This is a list where each item represents a package name.
logrotate_packages:
  - name: logrotate

# logrotate_config_directory: Specifies the directory where the main logrotate configuration is located.
logrotate_config_directory: /etc

# logrotate_config_file: The main logrotate configuration file.
# This is typically found inside the logrotate_config_directory.
logrotate_config_file: logrotate.conf

# logrotate_confd_directory: Specifies the directory for additional logrotate configuration files.
# These files are usually individual configurations for specific services or applications.
logrotate_confd_directory: "{{ logrotate_config_directory }}/logrotate.d"

# _logrotate_user: A dictionary defining the default user for log file ownership.
# This can be overridden based on the distribution.
_logrotate_user:
  default: root

# _logrotate_group: A dictionary defining the default group for log file ownership.
# This value varies depending on the Linux distribution.
_logrotate_group:
  default: root
  Debian: adm
  Ubuntu: adm
  AlmaLinux: root
  CentOS: root
  Rocky: root

# _logrotate_dateext: A dictionary to determine whether to append a date extension to rotated log files.
# The default behavior can be overridden for specific distributions.
_logrotate_dateext:
  default: false
  AlmaLinux: true
  CentOS: true
  Debian: false
  Rocky: true
  Ubuntu: false
