---

- name: Modify iptable Rules
  become: true
  ansible.builtin.iptables:
    action: "{{ iptables_rule_action | default(omit) }}"
    chain: "{{ iptables_rule_chain | default(omit) }}"
    comment: "{{ iptables_rule_comment | default(omit) }}"
    ctstate: "{{ iptables_rule_ctstate | default(omit) }}"
    destination: "{{ iptables_rule_destination | default(omit) }}"
    destination_port: "{{ iptables_rule_destination_port | default(omit) }}"
    destination_ports: "{{ iptables_rule_destination_ports | default(omit) }}"
    dst_range: "{{ iptables_rule_dst_range | default(omit) }}"
    flush: "{{ iptables_rule_flush | default(omit) }}"
    fragment: "{{ iptables_rule_fragment | default(omit) }}"
    gateway: "{{ iptables_rule_gateway | default(omit) }}"
    gid_owner: "{{ iptables_rule_gid_owner | default(omit) }}"
    goto: "{{ iptables_rule_goto | default(omit) }}"
    icmp_type: "{{ iptables_rule_icmp_type | default(omit) }}"
    in_interface: "{{ iptables_rule_in_interface | default(omit) }}"
    ip_version: "{{ iptables_rule_ip_version | default(omit) }}"
    jump: "{{ iptables_rule_jump | default(omit) }}"
    limit: "{{ iptables_rule_limit | default(omit) }}"
    limit_burst: "{{ iptables_rule_limit_burst | default(omit) }}"
    log_level: "{{ iptables_rule_log_level | default(omit) }}"
    log_prefix: "{{ iptables_rule_log_prefix | default(omit) }}"
    match: "{{ iptables_rule_match | default(omit) }}"
    match_set: "{{ iptables_rule_match_set | default(omit) }}"
    match_set_flags: "{{ iptables_rule_match_set_flags | default(omit) }}"
    out_interface: "{{ iptables_rule_out_interface | default(omit) }}"
    policy: "{{ iptables_rule_policy | default(omit) }}"
    protocol: "{{ iptables_rule_protocol | default(omit) }}"
    reject_with: "{{ iptables_rule_reject_with | default(omit) }}"
    rule_num: "{{ iptables_rule_rule_num | default(omit) }}"
    set_counters: "{{ iptables_rule_set_counters | default(omit) }}"
    set_dscp_mark: "{{ iptables_rule_set_dscp_mark | default(omit) }}"
    set_dscp_mark_class: "{{ iptables_rule_set_dscp_mark_class | default(omit) }}"
    source: "{{ iptables_rule_source | default(omit) }}"
    source_port: "{{ iptables_rule_source_port | default(omit) }}"
    src_range: "{{ iptables_rule_src_range | default(omit) }}"
    state: "{{ iptables_rule_state | default(omit) }}"
    syn: "{{ iptables_rule_syn | default(omit) }}"
    table: "{{ iptables_rule_table | default(omit) }}"
    tcp_flags: "{{ iptables_rule_tcp_flags | default(omit) }}"
    flags: "{{ iptables_rule_flags | default(omit) }}"
    flags_set: "{{ iptables_rule_flags_set | default(omit) }}"
    to_destination: "{{ iptables_rule_to_destination | default(omit) }}"
    to_ports: "{{ iptables_rule_to_ports | default(omit) }}"
    to_source: "{{ iptables_rule_to_source | default(omit) }}"
    uid_owner: "{{ iptables_rule_uid_owner | default(omit) }}"
    wait: "{{ iptables_rule_wait | default(omit) }}"
