---
- name: "Configure 'motd'"
  become: true
  ansible.builtin.template:
    src: "etc/update-motd.d/{{ item }}.j2"
    dest: "/etc/update-motd.d/{{ item }}"
    owner: root
    group: root
    mode: "755"
  loop:
    - 00-header
    - 02-facts
    - 03-sysinfo
    - 90-updates-available

- name: "Configure 'motd'"
  become: true
  ansible.builtin.template:
    src: "etc/motd.j2"
    dest: "/etc/motd"
    owner: root
    group: root
    mode: "755"

- name: Find files in the specified directory
  become: true
  ansible.builtin.find:
    paths: "/etc/update-motd.d/"
    file_type: file
  register: register_files_to_check

- name: Read contents of each file
  become: true
  ansible.builtin.slurp:
    src: "{{ item.path }}"
  loop: "{{ register_files_to_check.files }}"
  register: register_file_contents
  ignore_errors: true

- name: Delete files without the Ansible header
  become: true
  ansible.builtin.file:
    path: "{{ item.item.path }}"
    state: absent
  loop: "{{ register_file_contents.results }}"
  when: "'# Ansible managed' not in (item['content'] | b64decode).split('\n')[1]"
