---
- name: Include distribution install tasks
  ansible.builtin.include_tasks: "{{ loop_distribution }}"
  with_first_found:
    - files:
        - "install_logrotate_{{ distribution | lower }}_{{ distribution_version | lower }}.yml"
        - "install_logrotate_{{ distribution | lower }}_{{ distribution_major_version | lower }}.yml"
        - "install_logrotate_{{ distribution | lower }}.yml"
        - "install_logrotate_{{ ansible_os_family | lower }}.yml"
        - "install_logrotate_{{ ansible_system | lower }}.yml"
        - "defaults.yml"
  loop_control:
    loop_var: loop_distribution
  vars:
    distribution: "{{ ansible_distribution }}"
    distribution_version: "{{ ansible_distribution_version }}"
    distribution_major_version: "{{ ansible_distribution_major_version }}"

- name: Ensure logrotate tasks
  ansible.builtin.include_tasks: configure_logrotate.yml

- name: Ensure logrotate.d tasks
  ansible.builtin.include_tasks: configure_logrotate_d.yml
  vars:
    logrotate_d_name: "{{ logrotate_entrie.name | mandatory }}"
    logrotate_d_definitions: "{{ logrotate_entrie.definitions | mandatory }}"
  loop: "{{ logrotate_entries }}"
  loop_control:
    label: "{{ logrotate_entrie.name }}"
    loop_var: logrotate_entrie
