# Defines the timezone packages to be installed. It uses a conditional lookup based on the distribution.
# The variable "_timezone_packages" is a dictionary where each key is a distribution name (like 'CentOS', 'Ubuntu'),
# and the value is a list of package names. If the distribution is not found, it defaults to the 'default' key.
timezone_packages: "{{ _timezone_packages[ansible_distribution] | default(_timezone_packages['default']) }}"

# Sets the timezone name. The default value is set to "Etc/UTC".
# You can change this to your preferred timezone, for example, "America/New_York" or "Europe/Berlin".
timezone_name: "Etc/UTC"
