---
- name: "Deploy /etc/systemd/journald.conf"
  ansible.builtin.template:
    src: "etc/systemd/journald.conf.j2"
    dest: "/etc/systemd/journald.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - "Restart systemd-journald"

- name: Systemd-journald Service
  block:
    - name: 'Systemctl systemd-journald {{ systemd_journald_service_enabled | bool | ternary("enable", "disable") }}'
      ansible.builtin.systemd:
        name: "systemd-journald"
        enabled: "{{ systemd_journald_service_enabled }}"

    - name: "Systemctl systemd-journald {{ systemd_journald_service_state[:-2] }}"
      ansible.builtin.systemd:
        name: "systemd-journald"
        state: "{{ systemd_journald_service_state }}"
      register: "systemd_journald_service_state_result"

  rescue:
    - name: "Handle failure in managing systemd-journald service"
      ansible.builtin.debug:
        msg: "Failed to manage systemd-journald service. Please check the system logs for more information."

  always:
    - name: "Log completion of systemd-journald service management"
      ansible.builtin.debug:
        msg: "Completed systemd-journald service management block, regardless of outcome."
