---
- name: Run arillso Package
  ansible.builtin.include_role:
    name: arillso.system.packages
  vars:
    packages_list: "{{ pip_packages }}"

# - name: Update pip
#   ansible.builtin.pip:
#     name:
#       - pip
#       - setuptools
#     state: latest # noqa package-latest
#     executable: "{{ pip_executable | default(omit) }}"

- name: Ensure requested modules
  ansible.builtin.import_tasks: modules.yml
