---
- name: Install requested modules
  ansible.builtin.pip:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    executable: "{{ pip_executable | default(pip_executable) }}"
    extra_args: "{{ item.extra_args | default(pip_extra_args) }}"
  loop: "{{ pip_modules }}"
  loop_control:
    label: "{{ item.name }}"
