---
argument_specs:
  main:
    short_description: Manage APT packages
    description:
      - This specification manages the installation, update, and removal of APT packages on a system.
    options:
      apt_packages_list:
        type: list
        elements: dict
        description:
          - A list of APT packages to manage. Each entry can be a package name or a dictionary with additional options.
        default: []
        options:
          name:
            type: str
            description: The name of the APT package.
          version:
            type: str
            description: The version of the package to be installed or managed.
          install_recommends:
            type: bool
            description: Whether to install recommended packages along with the main package.
          allow_downgrade:
            type: bool
            description: Whether to allow downgrading of packages.
          purge:
            type: bool
            description: Whether to purge packages.
          force_apt_get:
            type: bool
            description: Whether to force the use of apt-get instead of apt.
          lock_timeout:
            type: int
            description: Lock timeout in seconds when installing packages.
          state:
            type: str
            description: The desired state of the package ('present', 'absent', 'latest', etc.).

      apt_packages_install_recommends:
        type: bool
        description: Default value for installing recommended packages. Used if not specified in the package list.
        default: true

      apt_packages_allow_downgrade:
        type: bool
        description: Default value for allowing package downgrades. Used if not specified in the package list.
        default: false

      apt_packages_purge:
        type: bool
        description: Default value for purging packages. Used if not specified in the package list.
        default: false

      apt_packages_force_apt_get:
        type: bool
        description: Default value for forcing the use of apt-get. Used if not specified in the package list.
        default: false

      apt_packages_lock_timeout:
        type: int
        description: Default value for the lock timeout. Used if not specified in the package list.
        default: 30

      apt_packages_state:
        type: str
        description: Default state of APT packages. Used if not specified in the package list.
        default: "present"
