---
# The maximum age (in seconds) of the package cache before it is considered stale and needs to be updated.
apt_cache_valid_time: 86400

# The maximum number of attempts to retry updating the cache if it fails.
apt_cache_update_cache_retries: 5

# The maximum delay (in seconds) between retry attempts when updating the cache.
apt_cache_update_cache_retry_max_delay: 12

# Whether to force the use of apt-get instead of apt when updating the cache.
apt_cache_force_apt_get: true
