- name: Check if reboot is required
  arillso.system.reboot_info:
  register: register_reboot

- name: Reboot the system
  when: register_reboot.reboot
  block:
    - name: Perform Reboot
      become: true
      ansible.builtin.reboot:
        reboot_timeout: "{{ reboot_timeout }}"
        pre_reboot_delay: "{{ reboot_pre_reboot_delay }}"
        msg: "{{ reboot_message }}"
        post_reboot_delay: "{{ reboot_post_reboot_delay }}"
        connect_timeout: "{{ reboot_connect_timeout }}"
        test_command: "{{ reboot_test_command }}"
        search_paths: "{{ reboot_search_paths }}"
        boot_time_command: "{{ reboot_boot_time_command }}"
        reboot_command: "{{ reboot_reboot_command }}"

    - name: Gather facts after reboot
      ansible.builtin.setup:

  rescue:
    - name: Handle reboot failure
      ansible.builtin.debug:
        msg: "Reboot has failed, please check the system manually."

  always:
    - name: Log reboot attempt
      ansible.builtin.debug:
        msg: "Reboot block execution completed, regardless of outcome."
