---

- name: Check if reboot requert
  arillso.system.reboot_info:
  register: register_reboot

- name: Reboot Block
  when: register_reboot.reboot
  block:
    - name: Reboot
      become: true
      ansible.builtin.reboot:
        reboot_timeout: "{{ reboot_timeout }}"
        pre_reboot_delay: "{{ reboot_delay }}"
        msg: "{{ reboot_message }}"
        post_reboot_delay: "{{ reboot_post_reboot_delay }}"

    - name: 3 gather facts after reboot
      ansible.builtin.setup:
