---
- name: Create APT configuration file for {{ apt_configuration_filename }}
  ansible.builtin.template:
    src: "etc/apt/apt.conf.d/apt_conf.j2"
    dest: "/etc/apt/apt.conf.d/{{ apt_configuration_filename }}"
    owner: root
    group: root
    mode: "0644"
