---
- name: Merge and Deduplicate APT Configurations
  when: apt_configuration_list | default([]) | length > 0
  block:
    - name: Merge Host-Specific APT Configurations
      ansible.builtin.set_fact:
        apt_configuration_list: "{{ apt_configuration_list | default([]) | union(apt_configuration_host_list | default([])) | unique }}"
      when: apt_configuration_host_list | default([]) | length > 0

    - name: Merge Group-Specific APT Configurations
      ansible.builtin.set_fact:
        apt_configuration_list: "{{ apt_configuration_list | union(apt_configuration_group_list | default([])) | unique }}"
      when: apt_configuration_group_list | default([]) | length > 0

- name: Ensure APT configuration
  block:
    - name: Create and apply APT configuration files
      ansible.builtin.include_tasks: "configuration.yml"
      loop: "{{ apt_configuration_list }}"
      loop_control:
        label: "{{ apt_configuration_filename }}"
      vars:
        apt_configuration_detail: "{{ item.config }}"
        apt_configuration_filename: "{{ item.filename }}"
