argument_specs:
  main:
    short_description: "Netplan configuration management for Linux"
    description:
      - This role manages network configurations using Netplan on Linux systems.
      - Supports DHCP and static IP configurations.
    options:
      netplan_packages:
        description: "List of packages for Netplan configuration."
        type: "list"
        elements: "dict"
      netplan_configurations:
        description: "Netplan network configurations."
        type: "list"
        elements: "dict"
        options:
          name:
            description: "Name of the configuration."
            type: "str"
            required: true
          content:
            description: "Netplan configuration in YAML format."
            type: "str"
            required: true
