---
- name: "Ensure package {{ dnf_package.name | default(omit) }}"
  become: true
  ansible.builtin.dnf:
    allow_downgrade: "{{ dnf_package_allow_downgrade | default(omit) }}"
    allowerasing: "{{ dnf_package_allowerasing | default(omit) }}"
    autoremove: "{{ dnf_package_autoremove | default(omit) }}"
    bugfix: "{{ dnf_package_bugfix | default(omit) }}"
    cacheonly: "{{ dnf_package_cacheonly | default(omit) }}"
    conf_file: "{{ dnf_package_conf_file | default(omit) }}"
    disable_gpg_check: "{{ dnf_package_disable_gpg_check | default(omit) }}"
    disable_plugin: "{{ dnf_package_disable_plugin | default(omit) }}"
    disablerepo: "{{ dnf_package_disablerepo | default(omit) }}"
    download_dir: "{{ dnf_package_download_dir | default(omit) }}"
    download_only: "{{ dnf_package_download_only | default(omit) }}"
    enable_plugin: "{{ dnf_package_enable_plugin | default(omit) }}"
    enablerepo: "{{ dnf_package_enablerepo | default(omit) }}"
    exclude: "{{ dnf_package_exclude | default(omit) }}"
    install_repoquery: "{{ dnf_package_install_repoquery | default(omit) }}"
    install_weak_deps: "{{ dnf_package_install_weak_deps | default(omit) }}"
    installroot: "{{ dnf_package_installroot | default(omit) }}"
    list: "{{ dnf_package_list | default(omit) }}"
    lock_timeout: "{{ dnf_package_lock_timeout | default(omit) }}"
    name: "{{ dnf_package_name }}{{ ('=' + dnf_package_version) if dnf_package_version else '' }}"
    nobest: "{{ dnf_package_nobest | default(omit) }}"
    releasever: "{{ dnf_package_releasever | default(omit) }}"
    security: "{{ dnf_package_security | default(omit) }}"
    skip_broken: "{{ dnf_package_skip_broken | default(omit) }}"
    sslverify: "{{ dnf_package_sslverify | default(omit) }}"
    state: "{{ dnf_package_state | default('present') }}"
    update_cache: "{{ dnf_package_update_cache | default(omit) }}"
    update_only: "{{ dnf_package_update_only | default(omit) }}"
    validate_certs: "{{ dnf_package_validate_certs | default(omit) }}"
