---

- name: ensure dnf packages
  ansible.builtin.include_tasks: install_dnf_package.yml
  vars:
    dnf_package_allow_downgrade: "{{ dnf_package.allow_downgrade | default(dnf_packages_allow_downgrade | default(omit)) }}"
    dnf_package_allowerasing: "{{ dnf_package.allowerasing | default(dnf_packages_allowerasing | default(omit)) }}"
    dnf_package_autoremove: "{{ dnf_package.autoremove | default(dnf_packages_autoremove | default(omit)) }}"
    dnf_package_bugfix: "{{ dnf_package.bugfix | default(dnf_packages_bugfix | default(omit)) }}"
    dnf_package_cacheonly: "{{ dnf_package.cacheonly | default(dnf_packages_cacheonly | default(omit)) }}"
    dnf_package_conf_file: "{{ dnf_package.conf_file | default(dnf_packages_conf_file | default(omit)) }}"
    dnf_package_disable_gpg_check: "{{ dnf_package.disable_gpg_check | default(dnf_packages_disable_gpg_check | default(omit)) }}"
    dnf_package_disable_plugin: "{{ dnf_package.disable_plugin | default(dnf_packages_disable_plugin | default(omit)) }}"
    dnf_package_disablerepo: "{{ dnf_package.disablerepo | default(dnf_packages_disablerepo | default(omit)) }}"
    dnf_package_download_dir: "{{ dnf_package.download_dir | default(dnf_packages_download_dir | default(omit)) }}"
    dnf_package_download_only: "{{ dnf_package.download_only | default(dnf_packages_download_only | default(omit)) }}"
    dnf_package_enable_plugin: "{{ dnf_package.enable_plugin | default(dnf_packages_enable_plugin | default(omit)) }}"
    dnf_package_enablerepo: "{{ dnf_package.enablerepo | default(omit) }}"
    dnf_package_exclude: "{{ dnf_package.exclude | default(omit) }}"
    dnf_package_install_repoquery: "{{ dnf_package.install_repoquery | default(omit) }}"
    dnf_package_install_weak_deps: "{{ dnf_package.install_weak_deps | default(omit) }}"
    dnf_package_installroot: "{{ dnf_package.installroot | default(omit) }}"
    dnf_package_list: "{{ dnf_package.list | default(omit) }}"
    dnf_package_lock_timeout: "{{ dnf_package.lock_timeout | default(dnf_packages_lock_timeout | default(omit)) }}"
    dnf_package_name: "{{ dnf_package.name }}"
    dnf_package_version: "{{ dnf_package.version | default('') }}"
    dnf_package_nobest: "{{ dnf_package.nobest | default(dnf_packages_nobest| default(omit)) }}"
    dnf_package_releasever: "{{ dnf_package.releasever | default(dnf_packages_releasever | default(omit)) }}"
    dnf_package_security: "{{ dnf_package.security | default(dnf_packages_security | default(omit)) }}"
    dnf_package_skip_broken: "{{ dnf_package.skip_broken | default(dnf_packages_skip_broken | default(omit)) }}"
    dnf_package_sslverify: "{{ dnf_package.sslverify | default(dnf_packages_sslverify | default(omit)) }}"
    dnf_package_state: "{{ dnf_package.state | default('present') }}"
    dnf_package_update_cache: "{{ dnf_package.update_cache | default(dnf_packages_update_cache | default(omit)) }}"
    dnf_package_update_only: "{{ dnf_package.update_only | default(dnf_packages_update_only | default(omit)) }}"
    dnf_package_validate_certs: "{{ dnf_package.validate_certs | default(dnf_packages_validate_certs | default(omit)) }}"
  loop: "{{ dnf_packages }}"
  loop_control:
    label: "{{ dnf_package_name }}"
    loop_var: dnf_package
