---

galaxy_info:
  role_name: sudoers
  author: arillso <team@arillso.io>
  description: Manage sudoers and sudoers.d in Linux.
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Alpine
      versions:
        - all
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - xenial
    - name: Debian
      versions:
        - bullseye
        - buster
        - sid

  galaxy_tags:
    - sudo
    - system

dependencies: []
