---
argument_specs:
  main:
    short_description: "Cross-platform user management"
    description:
      - This role manages user accounts on both Linux and Windows systems.
      - It applies OS-specific configurations and handles user attributes,
      - such as home directories, SSH keys, and permissions.
    options:
      users_list: &users_list
        description: "A list of users with their properties to be ensured on the system."
        type: "list"
        elements: "dict"
        required: true
        options:
          username:
            description: "The username of the account."
            type: "str"
            required: true
          uid:
            description: "The numeric user id for the user. Optional for system-generated IDs."
            type: "int"
            required: false
          home:
            description: "Home directory to create or manage. Optional if system default is used."
            type: "path"
            required: false
          comment:
            description: "The comment or full name for the user account. Optional, but recommended for clarity."
            type: "str"
            required: false
          system:
            description: "Specifies if the user is a system account. Default is false."
            type: "bool"
            required: false
          ssh_key_generate:
            description: "Indicates whether to generate SSH keys for the user. Default is false."
            type: "bool"
            required: false
          group:
            description: "Primary group for the user. Optional, system default is used if not specified."
            type: "str"
            required: false
          groups:
            description: "List of additional groups the user will be added to. Optional."
            type: "list"
            elements: "str"
            required: false
          append:
            description: "If true, additional groups are appended to the existing group list instead of replacing it."
            type: "bool"
            required: false
          password:
            description: "Password for the user, optionally hashed. Recommended for security."
            type: "str"
            required: false
          ssh_key_file:
            description: "Path to the SSH key file (relative to the home directory)."
            type: "str"
            required: false
          ssh_key_passphrase:
            description: "Passphrase for the generated SSH key. Optional."
            type: "str"
            required: false
          ssh_key_bits:
            description: "Number of bits for the generated SSH key. Optional, default depends on ssh-keygen."
            type: "int"
            required: false
          create_home:
            description: "Determines if the home directory should be created if it does not exist. Default is true."
            type: "bool"
            required: false
          shell:
            description: "The shell assigned to the user. Optional, defaults to system standard."
            type: "str"
            required: false
          update_password:
            description: "Determines whether to update the password if it differs from the current one. Optional."
            type: "str"
            required: false
          expires:
            description: "Account expiration time as an epoch timestamp. Optional."
            type: "float"
            required: false
          force:
            description: "Forces certain actions, such as overwriting an existing SSH key or removing an account."
            type: "bool"
            required: false
          local:
            description: "Use local commands for user management. Optional."
            type: "bool"
            required: false
          login_class:
            description: "Specifies the login class for the user (primarily BSD-specific). Optional."
            type: "str"
            required: false
          move_home:
            description: "Moves the user's home directory if it already exists. Optional."
            type: "bool"
            required: false
          password_expire_account_disable:
            description: "Number of days after which the account is disabled once the password expires. Optional."
            type: "int"
            required: false
          password_expire_max:
            description: "Maximum number of days between password changes (Linux only). Optional."
            type: "int"
            required: false
          password_expire_min:
            description: "Minimum number of days between password changes (Linux only). Optional."
            type: "int"
            required: false
          password_expire_warn:
            description: "Number of warning days before the password expires (Linux only). Optional."
            type: "int"
            required: false
          password_lock:
            description: "Specifies whether the password is locked. Optional."
            type: "bool"
            required: false
          profile:
            description: "Defines the user's profile (primarily Solaris-specific). Optional."
            type: "str"
            required: false
          remove:
            description: "Removes the user and associated directories (only with state=absent). Optional."
            type: "bool"
            required: false
          role:
            description: "Specifies the role of the user (primarily Solaris-specific). Optional."
            type: "str"
            required: false
          seuser:
            description: "Sets the SELinux user type (only relevant on SELinux-enabled systems). Optional."
            type: "str"
            required: false
          skeleton:
            description: "Specifies a skeleton directory for the home directory. Requires create_home. Optional."
            type: "str"
            required: false
          ssh_key_comment:
            description: "Comment to be added to the generated SSH key. Optional."
            type: "str"
            required: false
          umask:
            description: "Sets the umask for the user (Linux only). Optional."
            type: "str"
            required: false
          uid_min:
            description: "Minimum allowed UID value (Linux-specific). Optional."
            type: "int"
            required: false
          uid_max:
            description: "Maximum allowed UID value (Linux-specific). Optional."
            type: "int"
            required: false

      users_home:
        description: "Default home directory path for users. Default is '/home'."
        type: "path"
        default: "/home"
      users_group:
        description: "Default primary group for users. Not set by default."
        type: "str"
      users_groups:
        description: "List of default secondary groups for users. Defaults to an empty list."
        type: "list"
        elements: "str"
        default: []
      users_home_mode:
        description: "Default permissions for users' home directories. Default is '0755'."
        type: "str"
        default: "0755"
      users_ssh_key_type:
        description: "Default SSH key type for users. Default is 'rsa'."
        type: "str"
        default: "rsa"
      users_ssh_key_bits:
        description: "Default SSH key bit length for users. Default is 2048."
        type: "int"
        default: 2048
      users_authorized_keys_exclusive:
        description: "Whether to exclusively manage the 'authorized_keys' file. Default is 'no'."
        type: "str"
        default: "no"
      users_host_list: *users_list
      users_group_list: *users_list

  create_user_linux:
    short_description: "Linux user management"
    description:
      - This role manages Linux users, their home directories, SSH keys,
      - and file permissions based on OS-specific variables.
    options:
      users_list: *users_list

  create_user_windows:
    short_description: "Windows user management"
    description:
      - This section manages Windows user accounts, setting properties,
      - managing group memberships, and editing registry settings for user configurations.
    options:
      users_list: *users_list
