---
argument_specs:
  main:
    short_description: "Cross-platform user management"
    description:
      - This role manages user accounts on both Linux and Windows systems,
      - applying OS-specific configurations and handling user attributes
      - such as home directories, SSH keys, and permissions.
    options:
      users_list: &users_list
        description: "A list of users with their properties to be ensured on the system."
        type: "list"
        elements: "dict"
        required: true
        options:
          username:
            description: "The username of the account."
            type: "str"
            required: true
          uid:
            description: "The numeric user id for the user."
            type: "int"
            required: false
          home:
            description: "Home directory to create or manage."
            type: "path"
            required: false
          name:
            description: "Full name of the user."
            type: "str"
            required: false
          system:
            description: "Whether the user is a system account."
            type: "bool"
            required: false
          ssh_key_generate:
            description: "Whether to generate SSH keys for the user."
            type: "bool"
            required: false
          group:
            description: "Primary group for the user."
            type: "str"
            required: false
          groups:
            description: "List of groups the user will be added to."
            type: "list"
            elements: "str"
            required: false
          password:
            description: "Password for the user (optionally hashed)."
            type: "str"
            required: false
          shell:
            description: "The shell for the user."
            type: "str"
            required: false
          update_password:
            description: "Whether to update the password if it differs."
            type: "str"
            required: false
          authorized_keys:
            description: "SSH keys to add to the user's authorized_keys file."
            type: "list"
            elements: "str"
            required: false
      users_host_list: *users_list
      users_group_list: *users_list

  create_user_linux:
    short_description: "Linux user management"
    description:
      - This role manages Linux users, their home directories, SSH keys,
      - and file permissions based on OS-specific variables.
    options:
      users_list: *users_list

  create_user_windows:
    short_description: "Windows user management"
    description:
      - This section manages Windows user accounts, setting properties,
      - managing group memberships, and editing registry settings for user configurations.
    options:
      users_list: *users_list
