---
argument_specs:
  main:
    short_description: "Cross-platform log rotation management"
    description:
      - This role manages log rotation on both Linux and Windows systems.
      - It configures log rotation frequency, retention, compression, and ownership.
    options:
      logrotate_frequency:
        description: "Defines how often logs should be rotated. Options are 'daily', 'weekly', or 'monthly'."
        type: "str"
        required: false
        default: "weekly"
      logrotate_keep:
        description: "Specifies the number of rotated log files to keep."
        type: "int"
        required: false
        default: 4
      logrotate_compress:
        description: "Determines whether rotated logs should be compressed."
        type: "bool"
        required: false
        default: true
      logrotate_user:
        description: "Defines the user who will own the rotated log files, loaded from OS-specific variables or set manually."
        type: "str"
        required: false
      logrotate_group:
        description: "Defines the group that will own the rotated log files, loaded from OS-specific variables or set manually."
        type: "str"
        required: false
      logrotate_dateext:
        description: "Determines whether to append a date extension to the rotated log files."
        type: "bool"
        required: false
      logrotate_entries:
        description: "A list to define specific log rotation configurations."
        type: "list"
        elements: "dict"
        required: false
