---
- name: "Ensure yum repository {{ yum_repository_state }}"
  ansible.builtin.yum_repository:
    async: "{{ yum_repository_async }}"
    attributes: "{{ yum_repository_attributes }}"
    bandwidth: "{{ yum_repository_bandwidth }}"
    baseurl: "{{ yum_repository_baseurl }}"
    cost: "{{ yum_repository_cost }}"
    deltarpm_metadata_percentage: "{{ yum_repository_deltarpm_metadata_percentage }}"
    deltarpm_percentage: "{{ yum_repository_deltarpm_percentage }}"
    description: "{{ yum_repository_description }}"
    enabled: "{{ yum_repository_enabled }}"
    enablegroups: "{{ yum_repository_enablegroups }}"
    exclude: "{{ yum_repository_exclude }}"
    failovermethod: "{{ yum_repository_failovermethod }}"
    file: "{{ yum_repository_file }}"
    gpgcakey: "{{ yum_repository_gpgcakey }}"
    gpgcheck: "{{ yum_repository_gpgcheck }}"
    gpgkey: "{{ yum_repository_gpgkey }}"
    group: "{{ yum_repository_group }}"
    http_caching: "{{ yum_repository_http_caching }}"
    include: "{{ yum_repository_include }}"
    ip_resolve: "{{ yum_repository_ip_resolve }}"
    keepalive: "{{ yum_repository_keepalive }}"
    keepcache: "{{ yum_repository_keepcache }}"
    metadata_expire: "{{ yum_repository_metadata_expire }}"
    metadata_expire_filter: "{{ yum_repository_metadata_expire_filter }}"
    metalink: "{{ yum_repository_metalink }}"
    mirrorlist: "{{ yum_repository_mirrorlist }}"
    mirrorlist_expire: "{{ yum_repository_mirrorlist_expire }}"
    mode: "{{ yum_repository_mode }}"
    module_hotfixes: "{{ yum_repository_module_hotfixes }}"
    name: "{{ yum_repository_name }}"
    owner: "{{ yum_repository_owner }}"
    password: "{{ yum_repository_password }}"
    priority: "{{ yum_repository_priority }}"
    protect: "{{ yum_repository_protect }}"
    proxy: "{{ yum_repository_proxy }}"
    proxy_password: "{{ yum_repository_proxy_password }}"
    proxy_username: "{{ yum_repository_proxy_username }}"
    repo_gpgcheck: "{{ yum_repository_repo_gpgcheck }}"
    reposdir: "{{ yum_repository_reposdir }}"
    retries: "{{ yum_repository_retries }}"
    s3_enabled: "{{ yum_repository_s3_enabled }}"
    selevel: "{{ yum_repository_selevel }}"
    serole: "{{ yum_repository_serole }}"
    setype: "{{ yum_repository_setype }}"
    seuser: "{{ yum_repository_seuser }}"
    skip_if_unavailable: "{{ yum_repository_skip_if_unavailable }}"
    ssl_check_cert_permissions: "{{ yum_repository_ssl_check_cert_permissions }}"
    sslcacert: "{{ yum_repository_sslcacert }}"
    sslclientcert: "{{ yum_repository_sslclientcert }}"
    sslclientkey: "{{ yum_repository_sslclientkey }}"
    sslverify: "{{ yum_repository_sslverify }}"
    state: "{{ yum_repository_state }}"
    throttle: "{{ yum_repository_throttle }}"
    timeout: "{{ yum_repository_timeout }}"
    ui_repoid_vars: "{{ yum_repository_ui_repoid_vars }}"
    unsafe_writes: "{{ yum_repository_unsafe_writes }}"
    username: "{{ yum_repository_username }}"
