---
- name: Install nftables
  ansible.builtin.include_tasks: install.yml

- name: Configure nftables ruleset
  ansible.builtin.include_tasks: config.yml

- name: Manage nftables service
  ansible.builtin.include_tasks: service.yml
