---

- name: Ensure apt cache valid time
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time }}"
    update_cache_retries: "{{ apt_cache_update_cache_retries }}"
    update_cache_retry_max_delay: "{{ apt_cache_update_cache_retry_max_delay }}"
    force_apt_get: "{{ apt_cache_force_apt_get }}"

- name: Ensure apt cache is up to date
  ansible.builtin.meta: flush_handlers
