---

galaxy_info:
  description: This role checks if the system needs to be restarted and restarts it.
  author: "arillso (@arillso)"
  license: MIT
  min_ansible_version: "2.11"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    # - name: Windows
    #   versions:
    #     - all

  galaxy_tags:
    - reboot

dependencies: []
