---
- name: "Ensure systemd service {{ systemd_service_name }}"
  become: true
  when:
    - systemd_service_name | length
  block:
    - name: "Ensure systemd service enabled {{ systemd_service_name }}"
      ansible.builtin.systemd:
        name: "{{ systemd_service_name }}"
        enabled: "{{ systemd_service_enabled }}"

    - name: "Ensure systemd service started {{ systemd_service_name }}"
      ansible.builtin.systemd:
        name: "{{ systemd_service_name }}"
        state: "{{ systemd_service_state }}"

    - name: "Ensure systemd service reload {{ systemd_service_name }}"
      ansible.builtin.systemd:
        name: "{{ systemd_service_name }}"
        state: reloaded
      when:
        - systemd_service_reload_on

    - name: "Ensure systemd service restarted {{ systemd_service_name }}"
      ansible.builtin.systemd:
        name: "{{ systemd_service_name }}"
        state: restarted
      when:
        - systemd_service_restart_on

  rescue:
    - name: "Handle failure in managing systemd service {{ systemd_service_name }}"
      ansible.builtin.debug:
        msg: "Failed to manage systemd service {{ systemd_service_name }}. Check system logs for more information."

  always:
    - name: "Log completion of systemd service management for {{ systemd_service_name }}"
      ansible.builtin.debug:
        msg: "Completed systemd service management block for {{ systemd_service_name }}, regardless of outcome."
