---

- name: include distribution install tasks
  ansible.builtin.include_tasks: "{{ loop_distribution }}"
  with_first_found:
    - files:
        - "install_netplan_{{ distribution | lower }}_{{ distribution_version | lower }}.yml"
        - "install_netplan_{{ distribution | lower }}_{{ distribution_major_version | lower }}.yml"
        - "install_netplan_{{ distribution | lower }}.yml"
        - "install_netplan_{{ ansible_os_family | lower }}.yml"
        - "install_netplan_{{ ansible_system | lower }}.yml"
        - "defaults.yml"
  loop_control:
    loop_var: loop_distribution
  vars:
    distribution: "{{ ansible_distribution }}"
    distribution_version: "{{ ansible_distribution_version }}"
    distribution_major_version: "{{ ansible_distribution_major_version }}"

- name: include distribution configure tasks
  ansible.builtin.include_tasks: "{{ lookup('ansible.builtin.first_found', params) }}"
  loop_control:
    loop_var: netplan_configuration
    label: "/etc/netplan/{{ netplan_configuration.name }}.yaml"
  vars:
    distribution: "{{ ansible_distribution }}"
    distribution_version: "{{ ansible_distribution_version }}"
    distribution_major_version: "{{ ansible_distribution_major_version }}"
    params:
      files:
        - "configure_netplan_{{ distribution | lower }}_{{ distribution_version | lower }}.yml"
        - "configure_netplan_{{ distribution | lower }}_{{ distribution_major_version | lower }}.yml"
        - "configure_netplan_{{ distribution | lower }}.yml"
        - "configure_netplan_{{ ansible_os_family | lower }}.yml"
        - "configure_netplan_{{ ansible_system | lower }}.yml"
        - "defaults.yml"
  loop: "{{ netplan_configurations }}"
  when: netplan_configuration.name is defined
