---
argument_specs:
  main:
    short_description: Manages and configures systemd-journald service.
    description:
      - This role provides extensive configuration options for systemd-journald,
        the system service for collecting and storing log data on Linux systems.
      - It allows fine-tuning of various parameters such as log levels, storage,
        rate limiting, and log retention to suit different system requirements.
      - This role is designed to be flexible and is suitable for both small-scale
        deployments and large, complex systems.
    options:
      systemd_journald_compress:
        description: Whether to compress journal data.
        type: bool
        default: true

      systemd_journald_forward_to_console:
        description: Whether to forward journal messages to the system console.
        type: bool
        default: false

      systemd_journald_forward_to_kmsg:
        description: Whether to forward journal messages to the kernel logging buffer (kmsg).
        type: bool
        default: false

      systemd_journald_forward_to_syslog:
        description: Whether to forward journal messages to the system logger (syslog).
        type: bool
        default: true

      systemd_journald_forward_to_wall:
        description: Whether to forward urgent messages to all logged-in users.
        type: bool
        default: true

      systemd_journald_line_max:
        description: Maximum line length for journal messages.
        type: str
        default: "48K"

      systemd_journald_max_file_sec:
        description: Duration after which journal files are rotated.
        type: str
        default: "1month"

      systemd_journald_max_level_console:
        description: Maximum priority level of messages to be forwarded to the console.
        type: str
        default: "warning"

      systemd_journald_max_level_kmsg:
        description: Maximum priority level of messages to be forwarded to the kernel logging buffer (kmsg).
        type: str
        default: "notice"

      systemd_journald_max_level_store:
        description: Maximum priority level of messages to be stored in the journal.
        type: str
        default: "info"

      systemd_journald_max_level_syslog:
        description: Maximum priority level of messages to be forwarded to the system logger (syslog).
        type: str
        default: "info"

      systemd_journald_max_level_wall:
        description: Maximum priority level of urgent messages to be forwarded to all logged-in users.
        type: str
        default: "emerg"

      systemd_journald_max_retention_sec:
        description: Maximum retention period for journal entries.
        type: str
        default: "1month"

      systemd_journald_rate_limit_burst:
        description: Maximum number of messages recorded within the rate limit interval before limiting occurs.
        type: int
        default: 1000

      systemd_journald_rate_limit_interval:
        description: Time interval for rate limiting of log messages.
        type: str
        default: "30s"

      systemd_journald_runtime_keep_free:
        description: Keeps a specified amount of disk space free (empty means default is used).
        type: str
        default: ""

      systemd_journald_runtime_max_file_size:
        description: Maximum file size for runtime journal files (empty means default is used).
        type: str
        default: ""

      systemd_journald_runtime_max_files:
        description: Maximum number of runtime journal files.
        type: int
        default: 100

      systemd_journald_runtime_max_use:
        description: Maximum disk space to be used for runtime journal files (empty means default is used).
        type: str
        default: ""

      systemd_journald_seal:
        description: Whether to seal journal files.
        type: bool
        default: true

      systemd_journald_split_mode:
        description: How log messages are split among users (uid/login/none).
        type: str
        default: "uid"

      systemd_journald_storage:
        description: Defines where journal data is stored (persistent/volatile/auto/none).
        type: str
        default: "auto"

      systemd_journald_sync_interval_sec:
        description: Interval to synchronize journal data to disk.
        type: str
        default: "5m"

      systemd_journald_system_keep_free:
        description: Amount of disk space to keep free for system journal files.
        type: str
        default: "500M"

      systemd_journald_system_max_file_size:
        description: Maximum file size for system journal files.
        type: str
        default: "10M"

      systemd_journald_system_max_files:
        description: Maximum number of system journal files.
        type: int
        default: 100

      systemd_journald_system_max_use:
        description: Maximum disk space to be used for system journal files.
        type: str
        default: "1G"

      systemd_journald_service_enabled:
        description: Whether to enable the systemd journald service.
        type: bool
        default: true

      systemd_journald_service_state:
        description: Desired state of the systemd journald service (started/stopped/restarted/reloaded).
        type: str
        default: "started"
