---
# tasks file

- name: "Windows : check username length"
  ansible.builtin.fail:
    msg: "The username can be a maximum of 20 characters long."
  when: "item.username | length > 20"
  loop: "{{ users_list }}"
  loop_control:
    label: "{{ item.username }}"
  no_log: "{{ item.password is defined }}"

- name: "Windows : adding users"
  ansible.windows.win_user:
    name: "{{ item.username }}"
    fullname: "{{ item.name | default(omit) }}"
    description: "{{ item.description | default('Windows User') }}"
    password: "{{ item.password | default(omit) }}"
    groups: "{{ item.groups | default('Benutzer') }}"
    state: "{{ item.state | default('present') }}"
    account_disabled: "{{ item.account_disabled | default(false) }}"
    groups_action: "{{ item.groups_action | default('replace') }}"
    account_locked: "{{ item.account_locked | default(false) }}"
    password_never_expires: "{{ item.password_never_expires | default(true) }}"
    update_password: "{{ item.update_password | default('on_create') }}"
    password_expired: "{{ item.password_expired | default(false) }}"
    user_cannot_change_password: "{{ item.user_cannot_change_password | default(false) }}"
  loop: "{{ users_list }}"
  loop_control:
    label: "{{ item.username }}"
  no_log: "{{ item.password is defined }}"

- name: "Windows : hide user accounts from the login screen"
  ansible.windows.win_regedit:
    path: "{{ path }}\\CurrentVersion\\Winlogon\\SpecialAccounts\\UserList"
    name: "{{ item.username }}"
    type: dword
    data: "0" # You need to specify the data to set the registry value
  when: "item.hide | default(false)"
  loop: "{{ users_list }}"
  loop_control:
    label: "{{ item.username }}"
  no_log: "{{ item.password is defined }}"
  vars:
    path: "HKLM:\\SOFTWARE\\Microsoft\\Windows NT"

- name: "Windows : UAC enable"
  ansible.windows.win_regedit:
    path: "{{ path }}\\Windows\\CurrentVersion\\Policies\\System"
    name: EnableLUA
    type: dword
    data: "1"
  vars:
    path: "HKLM:\\SOFTWARE\\Microsoft"
