# tasks file

- name: Add OS specific variables
  ansible.builtin.include_vars:
    file: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "{{ ansible_system }}.yml"
        - "defaults.yml"
      paths: ["vars"]

- name: Add Users and Groups
  when: users_list is defined | bool
  block:
    - name: Add host users
      ansible.builtin.set_fact:
        users_list: "{{ users_list | union(users_host_list) | unique }}"
      when: users_host_list is defined | bool

    - name: Add group users
      ansible.builtin.set_fact:
        users_list: "{{ users_list | union(users_group_list) | unique }}"
      when: users_group_list is defined | bool

- name: Include distribution tasks
  ansible.builtin.include_tasks: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    distribution: "{{ ansible_distribution }}"
    distribution_version: "{{ ansible_distribution_version }}"
    distribution_major_version: "{{ ansible_distribution_major_version }}"
    params:
      files:
        - "create_user_{{ distribution | lower }}_{{ distribution_version | lower }}.yml"
        - "create_user_{{ distribution | lower }}_{{ distribution_major_version | lower }}.yml"
        - "create_user_{{ distribution | lower }}.yml"
        - "create_user_{{ ansible_os_family | lower }}.yml"
        - "create_user_{{ ansible_system | lower }}.yml"
        - "defaults.yml"
