---

- name: "ensure {{ sysctl_entrie_name }} entrie"
  become: true
  ansible.posix.sysctl:
    ignoreerrors: "{{ sysctl_entrie_ignoreerrors | default(omit) }}"
    name: "{{ sysctl_entrie_name | default(omit) }}"
    reload: "{{ sysctl_entrie_reload | default(omit) }}"
    state: "{{ sysctl_entrie_state | default(omit) }}"
    sysctl_file: "{{ sysctl_entrie_sysctl_file | default(omit) }}"
    sysctl_set: "{{ sysctl_entrie_sysctl_set | default(omit) }}"
    value: "{{ sysctl_entrie_value | default(omit) }}"
