---
- name: Ensure chocolatey packages
  ansible.builtin.include_tasks: install_chocolatey_package.yml
  vars:
    # Default values are provided using a consistent method for better readability.
    chocolatey_package_allow_empty_checksums: "{{ chocolatey_package.allow_empty_checksums | default(omit) }}"
    chocolatey_package_allow_multiple: "{{ chocolatey_package.allow_multiple | default(omit) }}"
    chocolatey_package_allow_prerelease: "{{ chocolatey_package.allow_prerelease | default(omit) }}"
    chocolatey_package_architecture: "{{ chocolatey_package.architecture | default(omit) }}"
    chocolatey_package_bootstrap_script: "{{ chocolatey_package.bootstrap_script | default(omit) }}"
    chocolatey_package_choco_args: "{{ chocolatey_package.choco_args | default(omit) }}"
    chocolatey_package_force: "{{ chocolatey_package.force | default(omit) }}"
    chocolatey_package_ignore_checksums: "{{ chocolatey_package.ignore_checksums | default(omit) }}"
    chocolatey_package_ignore_dependencies: "{{ chocolatey_package.ignore_dependencies | default(omit) }}"
    chocolatey_package_install_args: "{{ chocolatey_package.install_args | default(omit) }}"
    chocolatey_package_name: "{{ chocolatey_package.name }}"
    chocolatey_package_override_args: "{{ chocolatey_package.override_args | default(omit) }}"
    chocolatey_package_package_params: "{{ chocolatey_package.package_params | default(omit) }}"
    chocolatey_package_pinned: "{{ chocolatey_package.pinned | default(omit) }}"
    chocolatey_package_proxy_password: "{{ chocolatey_package.proxy_password | default(omit) }}"
    chocolatey_package_proxy_url: "{{ chocolatey_package.proxy_url | default(omit) }}"
    chocolatey_package_proxy_username: "{{ chocolatey_package.proxy_username | default(omit) }}"
    chocolatey_package_remove_dependencies: "{{ chocolatey_package.remove_dependencies | default(omit) }}"
    chocolatey_package_skip_scripts: "{{ chocolatey_package.skip_scripts | default(omit) }}"
    chocolatey_package_source: "{{ chocolatey_package.source | default(omit) }}"
    chocolatey_package_source_password: "{{ chocolatey_package.source_password | default(omit) }}"
    chocolatey_package_source_username: "{{ chocolatey_package.source_username | default(omit) }}"
    chocolatey_package_state: "{{ chocolatey_package.state | default('latest' if chocolatey_package.version == 'latest' else 'present') }}"
    chocolatey_package_timeout: "{{ chocolatey_package.timeout | default(omit) }}"
    chocolatey_package_validate_certs: "{{ chocolatey_package.validate_certs | default(omit) }}"
    chocolatey_package_version: "{{ chocolatey_package.version | default(omit) }}"
  loop: "{{ chocolatey_packages_list }}"
  loop_control:
    label: "{{ chocolatey_package_name }}"
    loop_var: chocolatey_package
