---
argument_specs:
  main:
    short_description: Configure and manage rsyslog environment using Ansible
    description:
      - This spec defines the parameters for configuring rsyslog and its environment on various distributions using Ansible.
    options:
      rsyslog_packages:
        type: list
        elements: str
        description: List of rsyslog packages to be installed.
        default: ["rsyslog"]

      rsyslog_service:
        type: str
        description: Name of the rsyslog service.
        default: "rsyslog"

      rsyslog_configuration:
        type: dict
        description: Main configuration for rsyslog including modules, global directives, and rules.
        options:
          modules:
            type: list
            elements: dict
            description: Configuration for rsyslog modules.
            options:
              name:
                type: str
                description: Name of the module.
              description:
                type: str
                description: Description of the module.
              settings:
                type: dict
                description: Specific settings for the module, varies by module.
                options:
                  input:
                    type: dict
                    description: Input settings for imudp and imtcp modules.
                    options:
                      type:
                        type: str
                        description: Type of the input, e.g., imudp or imtcp.
                      port:
                        type: int
                        description: Port number for UDP or TCP syslog reception.

          global_directives:
            type: dict
            description: Global directives for file ownership, permissions, and other settings.
            options:
              file_owner:
                type: str
                description: Default owner for log files.
              file_group:
                type: str
                description: Default group for log files.
              file_create_mode:
                type: str
                description: Permissions for new log files.
              dir_create_mode:
                type: str
                description: Permissions for new directories.
              umask:
                type: str
                description: Default umask for creating new files and directories.
              work_directory:
                type: str
                description: Work directory for rsyslog.
              include_config:
                type: str
                description: Include additional configuration files.

          rules:
            type: list
            elements: dict
            description: Defines rules for logging different types of messages.
            options:
              description:
                type: str
                description: Description of what the rule does.
              filter:
                type: str
                description: Filter defining which messages this rule applies to.
              action:
                type: str
                description: Action to take for messages matching the filter.
