---
galaxy_info:
  description: An Ansible role to configure rsyslog for logging management
  author: "arillso (@arillso)"
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: Ubuntu
      versions:
        - focal
        - bionic

  galaxy_tags:
    - logging
    - rsyslog
    - system
