---
galaxy_info:
  description: This role supports the maintenance of systems.
  author: "arillso (@arillso)"
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - maintenance

dependencies: []
