---
# Argument specifications for iptables rules

argument_specs:
  modify_iptables:
    description:
      - Manage iptables rules including creation, modification, and deletion.
    short_description: Manage iptables rules
    options:
      iptables_rule_action:
        description: Action to perform on the rule (append, insert, delete).
        default: append
        type: str

      iptables_rule_chain:
        description: Name of the iptables chain to modify (e.g., INPUT, FORWARD, OUTPUT).
        default: INPUT
        type: str

      iptables_rule_comment:
        description: Comment associated with the rule.
        type: str
        default: "{{ omit }}"

      iptables_rule_ctstate:
        description: Connection tracking states to match (e.g., NEW, ESTABLISHED).
        type: str
        default: "{{ omit }}"

      iptables_rule_destination:
        description: Destination address or network to match.
        type: str
        default: "{{ omit }}"

      iptables_rule_destination_port:
        description: Single destination port to match.
        type: str
        default: "{{ omit }}"

      iptables_rule_destination_ports:
        description: Range or multiple destination ports to match.
        type: str
        default: "{{ omit }}"

      iptables_rule_dst_range:
        description: Destination address range to match.
        type: str
        default: "{{ omit }}"

      iptables_rule_flush:
        description: Flush rules in the specified chain.
        type: bool
        default: "{{ omit }}"

      iptables_rule_fragment:
        description: Match fragmented packets.
        type: bool
        default: "{{ omit }}"

      iptables_rule_gateway:
        description: Gateway to use for redirected packets.
        type: str
        default: "{{ omit }}"

      iptables_rule_gid_owner:
        description: Group ID to match for ownership.
        type: int
        default: "{{ omit }}"

      iptables_rule_goto:
        description: Target chain to jump to for 'GOTO' action.
        type: str
        default: "{{ omit }}"

      iptables_rule_icmp_type:
        description: ICMP type to match.
        type: str
        default: "{{ omit }}"

      iptables_rule_in_interface:
        description: Incoming interface to match (e.g., eth0).
        type: str
        default: "{{ omit }}"

      iptables_rule_ip_version:
        description: IP version to use (ipv4, ipv6).
        type: str
        default: "{{ omit }}"

      iptables_rule_jump:
        description: Target chain to jump to for 'JUMP' action.
        type: str
        default: "{{ omit }}"

      iptables_rule_limit:
        description: Rate limit matching for a rule.
        type: str
        default: "{{ omit }}"

      iptables_rule_limit_burst:
        description: Maximum burst rate allowed before the limit rule applies.
        type: str
        default: "{{ omit }}"

      iptables_rule_log_level:
        description: Log level for logging rule matches.
        type: str
        default: "{{ omit }}"

      iptables_rule_log_prefix:
        description: Prefix for log messages.
        type: str
        default: "{{ omit }}"

      iptables_rule_match:
        description: Match criteria for the rule.
        type: str
        default: "{{ omit }}"

      iptables_rule_match_set:
        description: Match set for 'ipset' match.
        type: str
        default: "{{ omit }}"

      iptables_rule_match_set_flags:
        description: Flags for the 'ipset' match.
        type: str
        default: "{{ omit }}"

      iptables_rule_out_interface:
        description: Outgoing interface to match (e.g., eth1).
        type: str
        default: "{{ omit }}"

      iptables_rule_policy:
        description: Policy to set on the chain (e.g., ACCEPT, DROP).
        type: str
        default: "{{ omit }}"

      iptables_rule_protocol:
        description: Network protocol to match (e.g., tcp, udp, icmp).
        type: str
        default: "{{ omit }}"

      iptables_rule_reject_with:
        description: Option for rejecting packets.
        type: str
        default: "{{ omit }}"

      iptables_rule_rule_num:
        description: Rule number to insert/delete a specific rule.
        type: int
        default: "{{ omit }}"

      iptables_rule_set_counters:
        description: Set packet and byte counters for a rule.
        type: list
        default: "{{ omit }}"

      iptables_rule_set_dscp_mark:
        description: Set DSCP mark in the IP header.
        type: str
        default: "{{ omit }}"

      iptables_rule_set_dscp_mark_class:
        description: Set DSCP class in the IP header.
        type: str
        default: "{{ omit }}"

      iptables_rule_source:
        description: Source address or network to match.
        type: str
        default: "{{ omit }}"

      iptables_rule_source_port:
        description: Single source port to match.
        type: str
        default: "{{ omit }}"

      iptables_rule_src_range:
        description: Source address range to match.
        type: str
        default: "{{ omit }}"

      iptables_rule_state:
        description: State of the rule (present, absent).
        type: str
        default: present

      iptables_rule_syn:
        description: Match SYN packets.
        type: bool
        default: "{{ omit }}"

      iptables_rule_table:
        description: Table to apply the rule (e.g., filter, nat).
        type: str
        default: filter

      iptables_rule_tcp_flags:
        description: TCP flags to match.
        type: str
        default: "{{ omit }}"

      iptables_rule_flags:
        description: Custom flags to match.
        type: str
        default: "{{ omit }}"

      iptables_rule_flags_set:
        description: Set of flags to match.
        type: str
        default: "{{ omit }}"

      iptables_rule_to_destination:
        description: Target IP address for DNAT/SNAT.
        type: str
        default: "{{ omit }}"

      iptables_rule_to_ports:
        description: Target port(s) for DNAT/SNAT.
        type: str
        default: "{{ omit }}"

      iptables_rule_to_source:
        description: Source IP address for SNAT.
        type: str
        default: "{{ omit }}"

      iptables_rule_uid_owner:
        description: User ID to match for ownership.
        type: int
        default: "{{ omit }}"

      iptables_rule_wait:
        description: Wait time for xtables lock.
        type: int
        default: "{{ omit }}"

  # Hier können weitere Argument-Spezifikationen hinzugefügt werden
  main:
    description:
      - Manage iptables rules including creation, modification, and deletion.
    short_description: Manage iptables rules
    options:
      iptables_rules:
        description:
          - List of iptables rules to be managed.
          - Each item in the list is a dict that specifies parameters of a rule.
        type: list
        elements: dict
        default: []
        options:
          chain:
            description: Specifies the chain where the rule will be added (e.g., INPUT, FORWARD, OUTPUT).
            type: str

          action:
            description: Action to perform on the rule (append, insert, delete).
            type: str
            default: append

          protocol:
            description: Network protocol to match (e.g., tcp, udp, icmp).
            type: str

          source:
            description: Source address or network to match.
            type: str

          destination:
            description: Destination address or network to match.
            type: str

          destination_port:
            description: Single destination port to match.
            type: str

          source_port:
            description: Single source port to match.
            type: str

          in_interface:
            description: Incoming interface to match (e.g., eth0).
            type: str

          out_interface:
            description: Outgoing interface to match (e.g., eth1).
            type: str

          comment:
            description: Comment associated with the rule.
            type: str

          jump:
            description: Target chain to jump to for 'JUMP' action.
            type: str

          goto:
            description: Target chain to jump to for 'GOTO' action.
            type: str

          state:
            description: State of the rule (e.g., present, absent).
            type: str
            default: present

          table:
            description: Table to apply the rule (e.g., filter, nat).
            type: str
            default: filter
