---

galaxy_info:
  description: "Installs and configures iptables"
  author: "arillso (@arillso)"
  license: MIT
  min_ansible_version: "2.11"
  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: Ubuntu
      versions:
        - focal

  galaxy_tags:
    - networking

dependencies: []
