---
galaxy_info:
  description: apt cache role
  author: "arillso (@arillso)"
  license: MIT
  min_ansible_version: "2.11"
  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: Ubuntu
      versions:
        - focal

  galaxy_tags:
    - cache
    - apt

dependencies: []
