---
- name: Converge — arillso.system.ansible
  hosts: all
  become: true

  vars:
      ansible_install_enabled: true
      ansible_timer_enabled: false
      ansible_mode: pull
      ansible_repo: https://example.com/placeholder.git
      ansible_install_method: pipx
      ansible_ssh_key_enabled: false
      ansible_remove_system_package: false

  tasks:
      - name: Apply ansible role
        ansible.builtin.include_role:
            name: arillso.system.ansible
