---
# defaults file for reboot

# How long to wait before sending a reboot.
reboot_delay: 4

# Number of seconds to wait before checking if the machine is up.
reboot_up_delay: 8

# You can specify a message for rebooting, easier for auditing.
reboot_message: "Ansible role arillso.system.reboot initiated a reboot."

reboot_timeout: 30

reboot_post_reboot_delay: 30
