---
# Name of the systemd unit.
systemd_unit_name: ""

# Type of the systemd unit (e.g., service, timer).
systemd_unit_type: ""

# Default directory for systemd unit files.
systemd_unit_directory: /etc/systemd/system

# Full path for the systemd unit file, constructed using the directory, unit name, and type.
systemd_unit_file: "{{ systemd_unit_directory }}/{{ systemd_unit_name }}.{{ systemd_unit_type }}"

# Name of the override file for the systemd unit.
systemd_unit_override_name: ""

# Directory for the systemd unit override files, specific to the unit name and type.
systemd_unit_override_directory: "{{ systemd_unit_directory }}/{{ systemd_unit_name }}.{{ systemd_unit_type }}.d"

# Full path for the systemd unit override file, constructed using the override directory and override name.
systemd_unit_override_file: "{{ systemd_unit_override_directory }}/{{ systemd_unit_override_name }}.conf"

# List of supported systemd unit types (e.g., service, timer).
systemd_unit_types_supported:
  - service
  - timer

# Generic options for systemd units, applied regardless of the unit type.
systemd_unit_generic_options: []

# Specific options for the systemd unit, dependent on the unit type and configuration.
systemd_unit_options: []

# Options related to the 'Install' section of a systemd unit file.
systemd_unit_install_options: []
