---
# List of rsyslog packages to be installed
rsyslog_packages:
  - name: rsyslog # The main package for rsyslog

# Name of the rsyslog service
rsyslog_service: rsyslog

# Main configuration for rsyslog including modules, global directives, and rules
rsyslog_configuration:
  modules:
    - name: imuxsock # Module for local system logging
      description: "provides support for local system logging"
    - name: imklog # Module for kernel logging support
      description: "provides kernel logging support"
    - name: immark
      description: "provides --MARK-- message capability"
    - name: imudp
      description: "provides UDP syslog reception"
      settings:
        input:
          type: imudp
          port: 514
    - name: imtcp
      description: "provides TCP syslog reception"
      settings:
        input:
          type: imtcp
          port: 514

  global_directives:
    file_owner: root # Default owner for log files
    file_group: adm # Default group for log files
    file_create_mode: "0640" # Permissions for new log files
    dir_create_mode: "0755" # Permissions for new directories
    umask: "0022" # Default umask for creating new files and directories
    work_directory: "/var/spool/rsyslog" # Work directory for rsyslog
    include_config: "/etc/rsyslog.d/*.conf" # Include additional configuration files

  rules:
    - description: "Log anything besides private authentication messages to a single log file"
      filter: "*.*;auth,authpriv.none"
      action: "-/var/log/syslog"
    - description: "Log commonly used facilities to their own log file"
      filter: "auth,authpriv.*"
      action: "/var/log/auth.log"
    - filter: "cron.*"
      action: "-/var/log/cron.log"
    - filter: "kern.*"
      action: "/var/log/kern.log"
    - filter: "mail.*"
      action: "/var/log/mail.log"
    - filter: "user.*"
      action: "-/var/log/user.log"
    - description: "Emergencies are sent to everybody logged in"
      filter: "*.emerg"
      action: ":omusrmsg:*"
