---
iptables_packages:
  - iptables
  - iptables-persistent

iptables_service: iptables
iptables_6_service: ip6tables
iptables_configuration: /etc/iptables/rules.v4
iptables_6_configuration: /etc/iptables/rules.v6
