---
iptables_packages:
  - iptables
  - iptables-persistent

iptables_service: netfilter-persistent
iptables_6_service: netfilter-persistent
iptables_configuration: /etc/iptables/rules.v4
iptables_6_configuration: /etc/iptables/rules.v6
