---
- name: Ensure apt keys
  become: true
  ansible.builtin.apt_key:
    id: "{{ apt_key.id }}"
    url: "{{ apt_key.url }}"
    state: "{{ apt_key.state | default(apt_keys_state) }}"
  notify: ensure apt cache
  loop: "{{ apt_keys_list }}"
  loop_control:
    loop_var: apt_key
