---
name: Merge to Main
run-name: |
    Merge to Main by @${{ github.actor }}

on:
    push:
        branches: [main]
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: false

permissions:
    contents: read
    security-events: write
    actions: read
    pull-requests: read

jobs:
    ci:
        uses: arillso/.github/.github/workflows/ci-ansible-collection.yml@2026-06-12
        with:
            collection_namespace: arillso
            collection_name: system
            # renovate: datasource=github-releases depName=python/cpython extractVersion=^v(?<version>3\.\d+)
            python_version: "3.12"
            enable_unit_tests: true

    security-secrets:
        uses: arillso/.github/.github/workflows/security-secrets.yml@2026-06-12
