---
name: Publish Collection

on:
    push:
        tags:
            - "[0-9]+.[0-9]+.[0-9]+"

permissions:
    contents: write

jobs:
    publish:
        uses: arillso/.github/.github/workflows/release-ansible-collection.yml@2026-03-25
        with:
            collection_namespace: arillso
            collection_name: system
        secrets:
            galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
