galaxy_info:
  description: The role manages Python packages and modules installations using Pip on Linux systems.
  author: "arillso (@arillso)"
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Fedora
      versions:
        - all

  galaxy_tags:
    - python
    - pip
    - package
    - modules

dependencies: []
