---

galaxy_info:
  description: The role installs different packages on the dnf system.
  author: "arillso (@arillso)"
  license: MIT
  min_ansible_version: "2.11"
  platforms:
    - name: Centos
      versions:
        - all


  galaxy_tags:
    - package
    - packages
    - dnf
    - yum

dependencies: []
