---
galaxy_info:
  description: The role installs different packages on the dnf system.
  author: "arillso (@arillso)"
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions:
        - "9"

  galaxy_tags:
    - package
    - packages
    - dnf
    - yum

dependencies: []
